name: client
description: A flutter Flutter client for networking-di-samples app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_riverpod: ^2.0.2
  get_it: ^7.2.0
  dio: ^4.0.6
  auto_route: ^5.0.2
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  package_info_plus: ^3.0.1
  http: ^0.13.5
  graphql: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.2
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - lang/en.json

